config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create]
    resources :comments, only: [:create]
    resources :movies, only: :show
  end

  resources :movies, only: [:new, :create, :index, :show]

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie, uniqueness: { scope: :list } # Can have same movie many times, same list many times but not together
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :list

  validates :opinion, presence: true, length: { minimum: 6, maximum: 255 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :movies, -> { distinct }, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, -> { distinct }, through: :bookmarks
  has_one_attached :photo

  validates :title, :overview, presence: true
  validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [:create, :new]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = params[:list_id]
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_list, only: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.list_id = params[:list_id]
    if @comment.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:opinion)
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @comment = Comment.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    if params[:list_id]
      @list = List.find(params[:list_id])
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :rating, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= render '/components/list_banner', list: @list %>

<div class="container">
  <div class="row">
    <div class="col my-4 mx-auto">
      <h1>Add a new movie to <%= @list.name %> list</h1>
    </div>
  </div>
  <div class="row">
    <div class="col mx-auto">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.association :movie %>
        <%= f.input :comment %>
        <%= f.submit %>
        <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col mx-auto mt-4">
      <%= link_to "Back to #{@list.name}", list_path(@list), class: "btn btn-sm btn-outline-secondary" %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsWatchList</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- For Boostrap responsiveness -->
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render '/components/navbar' %>
  <body>
    <%= yield %>
  </body>
  </html>

app/views/lists/_form.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<%= render '/components/index_banner' %>

<div class="container mb-5">
  <div class="row">
    <div class="col my-4 mx-auto d-flex justify-content-between align-items-center">
      <h1>All lists</h1>
      <div>
        <%= link_to "Add a list", new_list_path, class: "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
    <div class="card-container col-md-6 col-xl-4 my-3">
      <%= link_to list_path(list), class: "list-title" do %>
      <% if list.photo.attached?  %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key %>')">
          <%= list.name %>
        </div>
      <% end %>
      <% end %>
    </div>
  <% end %>
  </div>
</div>
</div>

app/views/lists/new.html.erb
<%= render '/components/index_banner' %>

<div class="container">
  <div class="row">
    <div class="col my-4 mx-auto">
      <h1>Add a new list</h1>
    </div>
  </div>
  <div class="row">
    <div class="col mx-auto">
      <%= render 'form', list: @list %>
    </div>
  </div>
  <div class="row">
    <div class="col mx-auto mt-4">
      <%= link_to "Back to lists", lists_path, class: "btn btn-sm btn-outline-secondary" %>
    </div>
  </div>

</div>

app/views/lists/show.html.erb
<%= render '/components/list_banner', list: @list %>

<div class="container mt-3 mb-5">
  <div class="row my-2">
    <div class="col my-4 mx-auto d-flex justify-content-between align-items-center">
      <h1><%= @list.name %></h1>
      <div>
        <%= link_to "Back to lists", lists_path, class: "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="movies-container col-xs-12 col-md-9 py-4">

      <% @list.bookmarks.each do |bookmark| %>


      <div class="card-info">
        <div class="card-info-infos justify-content-center">
          <p><em>"<%= bookmark.comment %>"</em></p>
        </div>

        <%= link_to list_movie_path(@list, bookmark.movie) do %>
        <img class="poster-fit-div" src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %>"/>
        <% end %>
        <div class="card-info-infos">
          <div>
            <h2 class="movie-title"><%= bookmark.movie.title %></h2>
            <p><%= bookmark.movie.overview %></p>
          </div>
          <%# @bookmark = Bookmark.find_by(movie: movie, list: @list) %>
          <%= link_to bookmark_path(bookmark), data: { confirm: "Are you sure?", method: :delete } do %>
          <%= image_tag 'delete-bin2.png', alt: "deletion icon", class: "card-info-user" %>
          <% end %>
        </div>
      </div>

      <% end %>

    </div>

    <div class="sidebar col-xs-12 col-md-3 py-4">
      <div class="container-sticky">
        <div class="sidebar-container">
          <h2>Add a movie to <%= @list.name %></h2>
          <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie %>
          <%= f.input :comment %>
          <%= f.submit %>
          <% end %>
        </div>
        <div class="sidebar-container" id="comments-form">
          <h2>Add comments on <%= @list.name %></h2>
          <%= simple_form_for [@list, @comment] do |f| %>
          <%= f.input :opinion %>
          <%= f.submit %>
          <% end %>
        </div>
        <div class="sidebar-container">
          <h2>Past comments</h2>
          <% @list.comments.each do |comment| %>
          <p><%= comment.opinion %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/movies/_form.html.erb
<%= simple_form_for movie do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :rating %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<%= render '/components/index_banner' %>

<div class="container mt-3 mb-5">
  <div class="row my-2">
    <div class="col my-4 mx-auto d-flex justify-content-between align-items-center">
      <h1>All movies</h1>
      <div>
        <%= link_to "Add a movie", new_movie_path, class: "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>

  <div class="row">

    <div class="movies-container">
      <% @movies.each do |movie| %>
        <div class="card-info">
          <%= link_to movie_path(movie) do %>
            <% if movie.photo.attached? %>
              <%= cl_image_tag movie.photo.key, class: "poster-fit-div" %>
            <% else %>
              <img class="poster-fit-div" src="<%= movie.poster_url %>" alt="<%= movie.title %>">
            <% end %>
          <% end %>
          <div class="card-info-infos">
            <div>
              <h2 class="movie-title"><%= movie.title %></h2>
              <p><%= movie.overview %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<%= render '/components/index_banner' %>

<div class="container">
  <div class="row">
    <div class="col my-4 mx-auto">
      <h1>Add a new movie</h1>
    </div>
  </div>
  <div class="row">
    <div class="col mx-auto">
      <%= render 'form', movie: @movie %>
    </div>
  </div>
  <div class="row">
    <div class="col mx-auto mt-4">
      <%= link_to "Back to movies", movies_path, class: "btn btn-sm btn-outline-secondary" %>
    </div>
  </div>

</div>

app/views/movies/show.html.erb
<%= render '/components/movie_banner', movie: @movie %>

<div class="container mt-3 mb-5">

  <div class="row">
    <div class="col my-4 mx-auto d-flex justify-content-between align-items-center">
      <h1><%= @movie.title %></h1>
      <div>
        <% if @list %>
          <%= link_to "Back to #{@list.name}", list_path(@list), class: "btn btn-outline-secondary" %>
        <% else %>
          <%= link_to "Back to movies", movies_path, class: "btn btn-outline-secondary" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">

    <div class="col-xs-12 col-md-6 py-4">
      <div class="card-info p-3">
        <% if @movie.photo.attached? %>
          <%= cl_image_tag @movie.photo.key, class: "poster-fit-div" %>
        <% else %>
          <img class="poster-fit-div" src="<%= @movie.poster_url %>" alt="<%= @movie.title %>">
        <% end %>
      </div>
    </div>

    <div class="col-xs-12 col-md-6 py-4">
      <div class="card-info p-3">
          <h2 class="movie-title"><%= @movie.title %></h2>
          <p><%= @movie.overview %></p>
          <p>
            <strong>Rating: </strong><%= @movie.rating %>
            <% @movie.rating.ceil.times do %>
            <i class="far fa-star text-gold"></i>
            <% end %>
          </p>
      </div>
    </div>
</div>
</div>